Compatible to mkdocs 1.1
mkdocs.utils no longer contains string_types (mkdocs.utils)

This should provide a smooth fallback.
My failed builds: 

```
ImportError: cannot import name 'string_types' from 'mkdocs.utils' (/usr/local/lib/python3.7/site-packages/mkdocs/utils/__init__.py)
```